### ISSUE TITLE
second build fails

### ISSUE THREAD

**Issue by ghost** [aidecoe/qubes-builder-gentoo#11]
Hi. Can you help me to  fix issue?
![gentoo-log](https://user-images.githubusercontent.com/49844258/67150205-7854bb80-f282-11e9-8c45-b2d9425b6243.png)

**Comment by ghost** [comment]
Also please change README.
https://github.com/QubesOS/qubes-builder/commit/8407bc07b7a40ae40680fdde158469504d94d077#diff-a0f848942ce863cf53c0fa6cc684007d

you need to add lines to setup script
GPG_KEY_SERVER = ''keys.gnupg.net''
then find line " text = sh.gpg( " and add this lines  
'--keyserver',
GPG_KEY_SERVER,
 '--recv-keys',
key,
comment out 
 '--import',
 os.path.join(os.path.abspath(BASE_DIR), 'keys', key + '.asc'),

Also in qubes-builder folder remove script git-verity-tags (because it doesnt work)
and add false to script get-sources (check verity tags)

**Comment by aidecoe** [comment]
Was the previous build abruptly interrupted? Was everything unmounted?

**Comment by ghost** [comment]
> Was the previous build abruptly interrupted? Was everything unmounted?

I'm sorry, I can't check again because of my regular work, I made a Qubes Restore Backup and I have a ready gentoo-template. It works on all my machines. 17.1 profile, everything updated.
